"""ocrscout — scout frontier OCR models on your data, your hardware, your terms."""

from ocrscout._version import __version__
from ocrscout.errors import (
    BackendError,
    IntrospectionError,
    NormalizerError,
    PipelineError,
    ProfileError,
    RegistryError,
    ScoutError,
)
from ocrscout.interfaces import (
    BaselineView,
    Benchmark,
    Comparison,
    ComparisonRenderer,
    ComparisonResult,
    ExportAdapter,
    ModelBackend,
    Normalizer,
    PredictionView,
    ReferenceAdapter,
    Reporter,
    SourceAdapter,
)
from ocrscout.metrics import MetricsCollector
from ocrscout.profile import ModelProfile, dump_profile, load_profile, resolve
from ocrscout.registry import Registry, registry
from ocrscout.types import (
    AdapterRef,
    BackendInvocation,
    ExportRecord,
    PageImage,
    PipelineConfig,
    RawOutput,
    Reference,
    ReferenceProvenance,
    RunMetrics,
    Volume,
)

__all__ = [
    "AdapterRef",
    "BackendError",
    "BackendInvocation",
    "BaselineView",
    "Benchmark",
    "Comparison",
    "ComparisonRenderer",
    "ComparisonResult",
    "ExportAdapter",
    "ExportRecord",
    "IntrospectionError",
    "MetricsCollector",
    "ModelBackend",
    "ModelProfile",
    "Normalizer",
    "NormalizerError",
    "PageImage",
    "PipelineConfig",
    "PipelineError",
    "PredictionView",
    "ProfileError",
    "RawOutput",
    "Reference",
    "ReferenceAdapter",
    "ReferenceProvenance",
    "Registry",
    "RegistryError",
    "Reporter",
    "RunMetrics",
    "ScoutError",
    "SourceAdapter",
    "Volume",
    "__version__",
    "dump_profile",
    "load_profile",
    "registry",
    "resolve",
]
